### ISSUE TITLE
 Prior to starting the purchase users should be able to adjust product quantities, remove products, or cancel the entire shopping cart.

### ISSUE THREAD

**Issue by mehmetalicakir** [chingu-voyages/v40-toucans-team-08#22]

**Comment by mehmetalicakir** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/v40-toucans-team-08-62f168dc79b2880019736181/issues/chingu-voyages/v40-toucans-team-08/22?planning-poker) with ZenHub @droffilc1 @lordson-silver @SamJay321

**Comment by SamJay321** [comment]
Just voted
